name: Autograding Tests

on:
  push:
    branches: ["main"]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.run_number != 1 && !contains(github.event.repository.name, 'template')

    env: 
      BASE_COMMAND: dotnet test --nologo --no-restore --no-build

    steps:
    - uses: actions/checkout@v4

    - name: Restore .NET packages
      uses: actions/cache/restore@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - run: dotnet restore -v:q --locked-mode
    - run: dotnet build --no-restore -v:q

    - id: test-suite
      name: Running Test Suite
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Suite 1
        command: ${{ env.BASE_COMMAND }}
        max-score: 1

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test-suite.outputs.result}}"
      with:
        runners: Test

    - name: Save .NET packages
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
